### ISSUE TITLE
Example file loop.py errors

### ISSUE THREAD

**Issue by Racerx323** [SequentMicrosystems/SmartFan-rpi#1]
I get an error when I follow the instructions to use the example PID loop file loop.py.

Command and error:
~/SmartFan-rpi/python/examples $ python3 loop.py -t 50 -v
Traceback (most recent call last):
  File "loop.py", line 5, in <module>
    from gpiozero import CPUTemperature
ModuleNotFoundError: No module named 'gpiozero'

**Comment by alexburcea2877** [comment]
Hi, 

You need to install gpiozero library for python 3: "sudo apt install python3-gpiozero"
Thank you for reporting this I will put the instruction in the readme.

Alex.

**Comment by Racerx323** [comment]
Thank you! Works like a champ now.
