### ISSUE TITLE
Fan start with loop.py script

### ISSUE THREAD

**Issue by Racerx323** [SequentMicrosystems/SmartFan-rpi#2]
**Issue:** Fan blade does not start spinning until the fan power percentage requested is above approximately 25%. 
**Command used:** sudo python3 loop.py -t 40 -v
**Result:** The temperature will rise to 40. Once at 40, the fan blade will start 'stuttering' like it wants to start spinning. While the requested fan speed is less than 25%, the fan blade continues to stutter. The temperature rises enough to request 25% fan speed and the fan blade starts spinning. Once spinning, the fan blade spins up and down normally as the temperature varies above and below 40.

**Comment by alexburcea2877** [comment]
Hi,

This behavior was addressed in the fan firmware but we use slightly different design compared to prototypes that we use to develop the firmware.
You could fix this by adding a threshold before command the fan power (line 68 in the loop.py). I can do it after I receive the last version of the fan.

**Comment by Racerx323** [comment]
Are you saying there will be a future firmware update to address this?

**Comment by alexburcea2877** [comment]
No, there will be no firmware update, because the fan is not in system updatable. The only way to update the fan firmware will be with the JTAG probe. This why the fan is as dumb as possible and all the logic is transferred to the Raspberry.
This problem could be addressed in the software that controls the fan.

**Comment by Racerx323** [comment]
ah, okay. So the solution is to set the power threshold at 25% in the control software?

**Comment by alexburcea2877** [comment]
Yes.
