### ISSUE TITLE
fan command output

### ISSUE THREAD

**Issue by Racerx323** [SequentMicrosystems/SmartFan-rpi#3]
The fan command output references a command that does not work.
Output:
~ $ fan
        Usage:          fan -v
        Usage:          fan -h    Display commands list
        Usage:          fan -h <param>   Display help for <param> command
        Usage:          fan -warranty
        Usage:          fan -list
        Usage:          fan <stack> board
        Usage:          fan <id> prd
        Usage:          fan <id> pwr <power>
        Usage:          fan <id> strd
        Usage:          fan <id> stwr <temperature>
        Usage:          fan <id> trd
        Usage:          fan <id> bwr <blink>
        Usage:          fan <id> brd
        Usage:          fan <id> stopwr <time>
        Usage:          fan <id> stoprd
Where: <id> = Board level id = 0..1
Type ioplus -h <command> for more help

Command that does not work: Type **ioplus -h** <command> for more help

**Comment by alexburcea2877** [comment]
You find a bug in the help, I will fix this asap.
You need to add board level after "fan" command ex: "fan 0 pwr 50"
Thank you,
