### ISSUE TITLE
Error when running loop.py

### ISSUE THREAD

**Issue by joshschools** [SequentMicrosystems/SmartFan-rpi#4]
Not sure what I did wrong. Keep getting this error when trying to run loop.py

Command: ~/SmartFan-rpi/python/examples $ python3 loop.py -t 50 -v
Error: 
Traceback (most recent call last):
  File "loop.py", line 4, in <module>
    import sfan as f
ModuleNotFoundError: No module named 'sfan'

**Comment by alexburcea2877** [comment]
You need to install the "sfan" library first, instructions here: https://github.com/SequentMicrosystems/SmartFan-rpi/tree/main/python
Install it for python3 if you run the example on python3

**Comment by alexburcea2877** [comment]
I guess you solve the problem, I will close this old issue.
