### ISSUE TITLE
Error when using loop.py: "import sfan as f ImportError: No module named sfan"

### ISSUE THREAD

**Issue by moving-digital** [SequentMicrosystems/SmartFan-rpi#6]
Hello, I can seem to be able to use `loop.py` as I am getting the following error:

```
Traceback (most recent call last):
  File "loop.py", line 4, in <module>
    import sfan as f
ImportError: No module named sfan
```

Are you able to advise?

**Comment by moving-digital** [comment]
Hi, I installed `sfan` library folllowing the instructions here: https://github.com/SequentMicrosystems/SmartFan-rpi/tree/main/python

However now I'm getting a different error:

```
Traceback (most recent call last):
  File "loop.py", line 4, in <module>
    import sfan as f
  File "build/bdist.linux-aarch64/egg/sfan/__init__.py", line 1, in <module>
ImportError: No module named smbus
```

Now, it's not related to `sfan` but to `smbus`. Can someone adivse?

**Comment by moving-digital** [comment]
Finally got it working after installing `python3-smbus` that I forgot...

Closing the issue.

**Comment by jeremy-fields** [comment]
With pip being removed from Debian, use "apt install python3-smbus" instead.
